-- Storage bucket setup for APP PO documents (PDFs and Excel files)
-- 
-- IMPORTANT: The storage bucket AND policies must be created manually in Supabase Dashboard:
-- 
-- 1. CREATE BUCKET:
--    - Go to Storage section in Supabase Dashboard
--    - Click "New bucket"
--    - Name: documents
--    - Public: OFF (unchecked)
--    - File size limit: 52428800 (50MB) - optional
--    - Allowed MIME types: application/pdf, application/vnd.ms-excel, 
--      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet - optional
--
-- 2. CREATE POLICIES (in the bucket's policies tab):
--    - Policy 1: INSERT - "allow authenticated upload documents"
--      Allowed operation: INSERT
--      Target roles: authenticated
--      WITH CHECK: bucket_id = 'documents'
--
--    - Policy 2: SELECT - "allow authenticated read documents"
--      Allowed operation: SELECT
--      Target roles: authenticated
--      USING: bucket_id = 'documents'
--
--    - Policy 3: UPDATE - "allow authenticated update documents"
--      Allowed operation: UPDATE
--      Target roles: authenticated
--      USING: bucket_id = 'documents'
--      WITH CHECK: bucket_id = 'documents'
--
--    - Policy 4: DELETE - "allow authenticated delete documents"
--      Allowed operation: DELETE
--      Target roles: authenticated
--      USING: bucket_id = 'documents'
--
-- Both bucket and policy creation require elevated privileges and cannot be done via SQL migrations.

-- This migration file serves as documentation only

